---
title: Azusa High School, Custom Code
timezone: America/Los_Angeles
collections:
  uploads:
    title: Uploads
    output: true
permalink: pretty
exclude:
- README.md
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
